# 
# This file is for storing NON-SENSITIVE settings.
#
# Values here are loaded into the SETTINGS constant. For example, below you can
# access "Hello" through SETTINGS['say']['hello']
#
development: &default
  site:
    email: "sean@rocktree.us"

test:
  <<: *default

production:
  <<: *default
